# Gui 材质描述文件 模板（初稿）
# 整个文档格式为 TOML，文件名与材质名相同，且位于同一目录下
# 文档暂定 point, text, texture, slot, slots 五种基本元素和 progress, button 两种复合元素

# 图片文件尺寸
width = 256
height = 256

# 根节点中直接的整型数组可以表示一个点
title = [113, 5]

# 扩展的点
[a_point]
type = "point"
position = [0, 0]

# 文字
[text]
type = "text"
# 文字内容，默认以 lang key 处理
# 若存在 rawText 存在，则可省略
# 若 text 与 rawText 都不存在，则默认渲染 gui 的 getTitle
text = "examplemod.a_text"
# 文字内容，显示字符本身
# 若同时存在 text 和 rawText，仅显示 text 内容
# 若 text 与 rawText 都不存在，则默认渲染 gui 的 getTitle
rawText = ""
# 显示位置
position = [0, 0]
# 文字颜色
# 可省略，默认 0x808080
color = 0x808080
# 是否启用阴影，默认 false
shadow = false
# 剧中排序，默认 false
center = false

# 图形材质
[progress_filled]
type = "texture"
# 大小，类型 整形数组[2]
size = [17, 24]
# 材质大小，类型 整形数组[2]
# 默认与 size 相同
uv_size = [17, 24]
# 左上角位置，类型 整形数组[2]或省略
# 默认 [0, 0]
uv = [0, 181]
# 在 gui 中左上角位置
# 默认与 uv 相同，若用于其他控件（如 progress）则该属性无效
position = [0, 181]

[background]
type = "texture"
size = [225, 181]

# 一个物品框
[leaves]
type = "slot"
# 大小，类型 整形数组[2]或省略
# 可省略，默认 18
size = 18
# 左上角位置，类型 整形数组[2]
position = [201, 79]

# 一组物品框
[inventory]
type = "slots"
# 大小，类型 整形或省略
# 可省略，默认 18
size = 18
# 数量，类型 整形数组[2]/整形/省略，该实例表示一个有 3 行 9 列的物品框组
# 可简写为一个 整形 n，表示 [1, n] 或 [n, 1]，由 direction 属性控制
# 可省略 默认 [1, 1]
count = [3, 9]
# 左上角位置，类型 整形数组[2]
position = [30, 97]
# 两个 slot 之间的间隔，类型 整形数组[2]/整形/省略
# 可简写为一个 整形 n，表示 [n, 0] 或 [0, n]，由 direction 属性控制
# 可省略，默认 [0, 0]
offset = [0, 0]
# 方向，可选 horizontal/vertical
# 可省略，默认 horizontal
direction = "horizontal"

[selection]
type = "slots"
count = 9 # [1, 9]
position = [30, 155]

# 一个过程动画，类似熔炉的箭头
[a_progress]
type = "progress"
# 左上角位置
position = [5, 44]
# 进度为 0% 的材质名，类型：字符串，必须指向一个 type = "texture" 的表
# 可省略，可为空，表示无对应材质
texture = ""
# 进度为 100% 的材质名，类型：字符串，必须指向一个 type = "texture" 的表
texture_filled = "progress_filled"
# 方向，可选 horizontal/vertical/-horizontal/-vertical
# 可省略，默认 horizontal，即自左向右填充，带有 - 符号的表示相反方向（自右向左/自下而上）
direction = "horizontal"

[a_button]
type = "button"
# 左上角位置
position = [7, 99]
# 按钮尺寸
size = [1, 1]
# 普通状态材质名，类型：字符串数组，数组中每个元素必须指向一个 type = "texture" 的表
# 可省略，可为空，可为字符串，表示无对应材质
texture = [""]
# 鼠标悬浮材质名，类型：字符串数组，数组中每个元素必须指向一个 type = "texture" 的表
# 可省略，可为空，可为字符串，默认使用 texture
texture_hover = [""]
# 按下状态材质名，类型：字符串数组，数组中每个元素必须指向一个 type = "texture" 的表
# 可省略，可为空，可为字符串，默认使用 texture_hover
texture_pressed = [""]
# 按钮无效材质名，类型：字符串数组，数组中每个元素必须指向一个 type = "texture" 的表
# 可省略，可为空，可为字符串，默认使用 texture
texture_disable = [""]
# 鼠标悬浮时显示的提示，可以是 lang key
tooltip = ""

# 文本输入框，类似于告示牌的输入框
[a_editbox]
type = "editbox"
# 左上角位置
position = [0, 0]
# 大小
size = [0, 0]
# title，可省略，可以是 lang key
title = ""
# 提示，可以是 lang key
hint = ""
# 最大长度
# 可省略，默认 32
max_length = 32
# 是否有边框
# 可省略，默认为 false
bordered = true
# 可省略，不知道是啥
suggestion = ""
# 默认文本
# 可省略，默认为空
default = ""
# 文本颜色
# 可省略，默认 0xE0E0E0
color = 0xE0E0E0
# 不可编辑时的文本颜色
# 可省略，默认 0x707070
color_uneditable = 0xE0E0E0
# 没猜错的话是前景色？
# 可省略，默认 -1
color_fg = -1
# 透明度，0-1 浮点数
# 可省略，默认 1
alpha = 1
# 鼠标悬浮时显示的提示，可以是 lang key
tooltip = ""
